apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: dockerhub.ck/public/grafana:v4.4.3
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-dir
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-dir
        hostPath:
          path: /data/grafana

