apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: dockerhub.ck/public/prom-prometheus:v1.7.1
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: storage-dir
          mountPath: /prometheus
      nodeSelector:
        prometheus: "pt"
      serviceAccountName: prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: storage-dir
        hostPath:
          path: /data/prometheus
